version: '3.3'

services:
  dev:
    build:
      context: ".docker/"
      dockerfile: "Dockerfile"
    container_name: "${APP_NAME:-expressjs_dev}"
    command: [ "pm2-runtime", "start", "/usr/src/app/server.js", "--watch" ]
    image: expressjs:latest
    ports: [ "${PORT:-8080}:8080" ]
    volumes: [ "./:/usr/src/app" ]
    environment:
      APP_ENV: "${APP_ENV:-dev}"

  stable:
    build:
      context: ".docker/"
      dockerfile: "Dockerfile"
    container_name: "${APP_NAME:-expressjs_stable}"
    command: [ "pm2", "start", "/usr/src/app/server.js" ]
    image: expressjs:latest
    ports: [ "${PORT:-8080}:8080" ]
    volumes: [ "./:/usr/src/app" ]
    environment:
      APP_ENV: "${APP_ENV:-stable}"
    restart: always